[project]
name = "quantumfetcher"
version = "1.0.1"
description = ""
authors = [
    {name = "Marek Grzyb",email = "marek@grzyb.dev"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer (>=0.20.0,<0.21.0)",
    "requests (>=2.32.5,<3.0.0)",
    "inquirer (>=3.4.1,<4.0.0)",
    "humanreadable (>=0.4.1,<0.5.0)"
]

[tool.poetry]
packages = [{include = "quantumfetcher", from = "src"}]

[tool.poetry.scripts]
quantumfetcher = "quantumfetcher:app"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
